name: prec
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.8
  - pandas=1.3.3
  - pip
  - pip:
      - multimethod==1.7
      - toml==0.10.2
      - pytest==6.2.5
      - pre-commit==2.15.0