name: prec
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.8.20
  - pandas=1.3.3
  - mypy
  - pip
  - pip:
      - azureml.pipeline-core==1.59.0
      - azureml-pipeline-steps==1.59.0
      - azure-identity==1.19.0
      - azure-storage-blob==12.24.1
      - poetry==1.8.5
      - pytest==8.3.4
      - azureml-core==1.59.0
      - azureml-dataprep
      - multimethod==1.7
      - toml==0.10.2
      - pre-commit==2.15.0
      - pyarrow==17.0.0
      - scikit-learn==1.3.2
      - surprise==0.1
      - matplotlib==3.7.5
      - seaborn==0.13.2
