title = "Recommendation Engine Default Configuration"
# ==============================================================================
[args]
user_id = "userId"
item_id = "movieId"
data_folder = "data"

[args.data_loader]
    azure_account_url = ""
    azure_container_name = ""
    item_file = "movies.csv"
    rating_file = "ratings.csv"

[args.data_processor]
    validation_data_duration = 3
